config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get 'dashboard', to: 'reservations#dashboard'

  resources :spacecrafts do
    resources :reservations, only: [:new, :create]
  end

  resources :reservations, only: [:show, :update]
  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  enum reservation_status: {
    pending: 0,
    accepted: 1,
    rejected: 2
  }

  belongs_to :user
  belongs_to :spacecraft
  validates :comment, presence: true
end

app/models/spacecraft.rb
class Spacecraft < ApplicationRecord
  belongs_to :user
  has_one_attached :photo
  has_one_attached :personnage
  has_many :reservations, dependent: :destroy
  validates :name, :velocity, :passenger_capacity, :price, presence: true
  validates :name, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  # has_many :spacecrafts, :reservations
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :spacecrafts
  has_many :reservations
  has_one_attached :avatar

  validates_length_of :password, in: 6..20, on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :set_spacecraft, only: [ :new, :create ]

  def new
    @reservation = Reservation.new
    authorize @reservation
  end

  def create
    @reservation = Reservation.new(reservation_params)
    @reservation.user = current_user
    @reservation.spacecraft = Spacecraft.find(params[:spacecraft_id])
    authorize @reservation
    if @reservation.save
      redirect_to spacecraft_path(@spacecraft), notice: "Your reservation was successfully."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def dashboard
    @user = current_user
    @user_reservations = @user.reservations
    @user_spacecrafts = @user.spacecrafts
    @reservations = Reservation.all
    authorize @reservations
    # raise
  end

  def update
    @reservation = Reservation.find(params[:id])
    @reservation.update(status_params)
    authorize @reservation
  end

  private

  def set_spacecraft
    @spacecraft = Spacecraft.find(params[:spacecraft_id])
  end

  def reservation_params
    params.require(:reservation).permit(:comment)
  end

  def status_params
    params.require(:reservation).permit(:reservation_status)
  end
end

app/controllers/spacecrafts_controller.rb
class SpacecraftsController < ApplicationController
  before_action :set_spacecraft, only: %i[show edit update destroy]
  def index
    @spacecrafts = policy_scope(Spacecraft)
  end

  def show
  end

  def new
    @spacecraft = Spacecraft.new
    authorize @spacecraft
  end

  def create
    @spacecraft = Spacecraft.new(spacecraft_params)
    @spacecraft.user = current_user
    authorize @spacecraft
    if @spacecraft.save
      redirect_to spacecraft_path(@spacecraft), notice: 'spacecrafts was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @spacecraft.update(spacecraft_params)
      redirect_to spacecraft_path(@spacecraft)
    else
      render :edit
    end
  end

  def destroy
    @spacecraft.destroy
    redirect_to spacecrafts_path(@spacecraft)
  end

  private

  def set_spacecraft
    @spacecraft = Spacecraft.find(params[:id])
    authorize @spacecraft
  end

  def spacecraft_params
    params.require(:spacecraft).permit(:name, :velocity, :passenger_capacity, :price, :photo, :personnage)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SPACEBnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>

    <!-- Custom -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lora&family=Montserrat:wght@100&family=Roboto:wght@300&family=Share+Tech+Mono&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="home">
<%= render "shared/banner" %>
</div>

app/views/reservations/dashboard.html.erb
<div class="container dashboard">
  <h1>Dashboard</h1>
  <br>
  <div class="row">

    <div class="col-6">
      <h2>My reservations</h2>
          <% @user_reservations.each do |reservation| %>
          <div class="boite">
            <p>Reference No: <%= reservation.id %>000BNB </p>
            <p>Comment: <%= reservation.comment %></p>
            <p>Status: <%= reservation.reservation_status %></p>
            <p>Spaceship: <%= reservation.spacecraft.name %> </p>
          </div>
          <br>
        <% end %>
    </div>

    <div class="col-6">
      <h2>Requests &#40;your spaceship&#41;</h2>
      <% @reservations.each do |reservation| %>
        <% if reservation.user_id != @user.id %>
          <div class="boite my-2 p-2">
            <p>Reservation id: <%= reservation.id %></p>
            <p>Spacecraft: <%= reservation.spacecraft.name %></p>
            <p>Reservation id: <%= reservation.comment %></p>
            <p>Reservation status: <%= reservation.reservation_status %></p>

            <%= simple_form_for(reservation) do |f| %>
              <%= f.hidden_field :reservation_status, value: 'accepted' %>
              <%= f.submit :Accept %>
            <% end %> <!-- form Accept -->

            <%= simple_form_for(reservation) do |f| %>
              <%= f.hidden_field :reservation_status, value: 'rejected' %>
              <%= f.submit :Reject %>
            <% end %> <!-- form Accept -->
          </div> <!-- boite -->
        <% end %> <!-- if -->
      <% end %> <!-- each -->
    </div>

  </div>
</div>

app/views/reservations/new.html.erb
<!-- http://localhost:3000/spacecrafts/:id/reservations/new -->
<div class= "container2">
<h1>New Reservation</h1>

<%= simple_form_for([@spacecraft, @reservation]) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :comment %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn-flat" %>
  </div>
<% end %>
</div>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://astronomy.com/-/media/Images/News%20and%20Observing/News/2019/07/BFR_Sep_Longnose.jpg?mw=600);">
  <div class="container">
    <h1>SPACE BNB </h1>
    <h3><strong>Travel towards your dreams, go as far as you want to go!</strong></h3>
    <%= link_to "Check our Spaceships", spacecrafts_path, class: "btn btn-flat" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://previews.123rf.com/images/riops/riops1608/riops160800066/60648190-concepto-de-s%C3%ADmbolo-de-bot%C3%B3n-de-nave-espacial-azul-de-alta-calidad-en-el-fondo-gris.jpg" %>
      <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <span class ="nav-link"><%= current_user.email %></span>
          </li>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Spaceships", spacecrafts_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Post-spacecraft", new_spacecraft_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://thumbs.dreamstime.com/b/astronauta-en-traje-composici%C3%B3n-casco-espacial-realista-con-imagen-de-exposici%C3%B3n-cabeza-vidrio-fondo-transparente-ilustraci%C3%B3n-214944209.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/spacecrafts/_form.html.erb
<br>
<br>
<br>
<div id="simple-form">
  <%= simple_form_for(@spacecraft) do |f| %>
  <%= f.input :name , input_html: { class:"text-dark"}%>
  <%= f.input :velocity %>
  <%= f.input :passenger_capacity %>
  <%= f.input :price %>
  <%= f.input :photo, as: :file %>
  <%= f.input :personnage, as: :file %>
  <%= f.submit %>
  <% end %>
</div>

app/views/spacecrafts/_spacecrafts.html.erb
<h2>Spaceship: <%= @spacecraft.name %></h2>
<p>Speed: <%= @spacecraft.velocity %> km/s</p>
<p>Capacity: <%= @spacecraft.passenger_capacity %> passengers</p>
<p>Cost: <%= @spacecraft.price %> $</p>

app/views/spacecrafts/edit.html.erb
<h1>Edit a post</h1>
<%= render "form", spacecraft: @spacecraft %>

app/views/spacecrafts/new.html.erb
<br>
<div class="text-center">
  <h1 class="text-light">Create a post</h1>
  <%= render "form", spacecraft: @spacecraft %>
</div>